### PR TITLE
Feature (SC-382): poetry cleanup

### PR DESCRIPTION
**Pull request by gordon-epc**
Clean up various repo items in sunspec-demo related to the addition of poetry.

### CODE REVIEW

**Review by epcAnker — COMMENTED** [review]
Why get rid of the license file?

**Comment by gordon-epc** [comment]
> Why get rid of the license file?

I incorrectly thought that poetry would automatically add that file, but it doesn't. I undeleted.

**Review by epcAnker — APPROVED** [review]
are we fine removing gitattributes??

**Comment by gordon-epc** [comment]
> are we fine removing gitattributes??

The `.gitattributes` file is referencing `_version.py`, which has been removed. This is related to versioneer functionality, which has been removed.

**Pull request merged**
